alphagov/wcag-primer

source/documentation/1.3.4.md
source/documentation/1.3.5.md
source/documentation/1.4.10.md
source/documentation/1.4.11.md
source/documentation/1.4.12.md
source/documentation/1.4.13.md
source/documentation/2.1.4.md
source/documentation/2.5.1.md
source/documentation/2.5.2.md
source/documentation/2.5.3.md
source/documentation/2.5.4.md
source/documentation/4.1.3.md

I’ve separated these into their own branch - hopefully make it easier
for you to manage.

New 2.1 SCs only

---

source/documentation/checklist.md

Here are the questions for the checklist to cover the new 2.1 SCs

Updated checklist for 2.1

---

source/documentation/index.md

(Hopefully) final edit with formatting improved. [NEW] in bold for new
SCs - I removed the code/design/content identifiers from the earlier
version also.

More edits to index.html

---

source/documentation/_content.md.erb

Updates to Content page

---

source/documentation/_design.md.erb

Updates to Design Page

---

source/documentation/_code.md.erb

2.1 code page update

---

source/documentation/_all.md.erb

Update to All page

---

source/documentation/3.3.4.md

Changes to text and some new resources/techniques.

Changes to text of 3.3.4 and links to techniques

---

source/documentation/1.3.3.md

No need for resources on this one

Suggest removing TBC

---

source/documentation/1.4.1.md

I’ve found some interesting articles on colour blindness in gaming.
I’ve included them here. See if you think relevant.

Editorial suggestions for 1.4.1 and some extra resources

---

source/documentation/index.md

> <del>wwho</del> <ins>who</ins>

Fix minor typo

---

source/documentation/1.2.2.md
source/documentation/2.4.5.md
source/documentation/3.1.2.md
source/documentation/3.3.3.md
source/documentation/3.3.4.md

Some of the levels were incorrect for some of the criterion so I've gone through and updated these in this PR.

Update crition names to have correct level (A, AA)

---

source/documentation/checklist.md

The checklist questions for 2.5.1 and 2.5.4 were missing parts.
https://github.com/alphagov/wcag-primer/issues/19
There was an error in the checklist question for 2.5.2.
https://github.com/alphagov/wcag-primer/issues/20

Fixes some errors in checklist questions about 2.5.1, 2.5.2 and 2.5.4

---

source/documentation/1.3.5.md

Preserve line breaks and enable syntax highlighting for code block.

Improve code example

---

source/documentation/_all.md.erb

This fixes the following issue: https://github.com/alphagov/wcag-primer/issues/22

Removed 1.3.2 duplication in 'all requirements' file

---

config/tech-docs.yml
source/accessibility.html.md.erb
source/documentation/checklist.md
source/documentation/index.md

This PR makes some accessibility fixes to the content, and also publishes an accessibility statement for the content. This is separate to the statement on the tech doc template itself, which is in a separate location but is linked to from this statement.

Accessibility fixes and statement

---

source/documentation/checklist.md
source/documentation/index.md

Improving 2.5.1
Update [found on this PR](https://github.com/alphagov/wcag-primer/pull/38/files) + additional adjustments to improve Content

Update Content for 2.5.1

---

source/documentation/2.1.1.md
source/documentation/index.md

Update docs via related PR: https://github.com/alphagov/wcag-primer/pull/34

Update 2.1.1 (Jfhector)

---

source/partials/_internal-banner.html.erb

This change adds a link to a survey to help people share their views on the WCAG Primer.

Add survey link

---

source/sc/3.1.1.html.md.erb

This pull request completely rewrites and expands on success criterion 3.1.1 Language of Page in line with our updated template.
Written by @querkmachine and reviewed by me. I've checked it locally and it works for me.

Rewrite 3.1.1 Language of Page
